config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get '/login', to: "home#login"

  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  # resources :guests, only: [:create, :destroy]

  resources :rooms, only: [:new, :create, :show]
  post '/rooms/join', to: 'rooms#join', as: 'rooms_join'
  delete '/rooms/:room_id/leave/:player_num', to: 'rooms#leave', as: 'rooms_leave'
  post '/rooms/:id/start', to: 'rooms#start', as: 'room_game_start'
  post '/rooms/:id/finish', to: 'rooms#finish', as: 'room_game_finish'
  patch '/rooms/:room_id/get_admin/:player_num', to: 'rooms#get_admin', as: 'room_get_admin'
end

app/models/user.rb
class User < ApplicationRecord
  include Player

  has_one :room_player, as: :player
  has_many :rooms, through: :room_players
  has_many :purchased_items
  has_many :items, through: :purchased_items
  
  attr_accessor :old_password
  has_secure_password validations: false

  validates :login, presence: true
  validate :login_complexity, if: -> { login.present? }
  validates :login, uniqueness: true, if: -> { login.present? }
  validates :password, confirmation: true, allow_blank: true, length: { minimum: 8, maximum: 32 }
  validate :password_complexity, if: -> { password.present? }
  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? || login_changed? }
  
  before_validation :downcase_login
  before_save :set_valid_nickname

  def initialize(attributes = {})
    super
    self.nickname ||= "Player_#{SecureRandom.hex(4)}"
  end

  def avatar
    current_purchased_item = purchased_items.joins(:item).find_by(current: true, items: { itemable_type: 'Avatar' })
    return current_purchased_item.item.itemable if current_purchased_item
    return Avatar.default
  end

  private 

  def downcase_login
    self.login&.downcase!
  end

  def login_complexity
    return if login =~ /\A[a-zA-Z0-9_]+\z/
    errors.add :login, 'complexity requirement not met. Login should include only digits, uppercases, lowercases and underscore'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*\.\-_])/
    errors.add :password, 'complexity requirement not met. Password should include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

  def password_presence
    errors.add(:password, :blank) unless password_digest.present?
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)
    errors.add :old_password, 'is incorrect'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_no_authenticate, only: [:new, :create]
  before_action :check_authenticate, only: [:update]

  def new
    @user ||= User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      sign_in_user(@user)
      flash[:success] = "Successful registration"
      # redirect_to edit_user_path
    else
      flash[:error] = "Unable to save"
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  # def edit 
        
  # end

  def update
        
  end

  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation, :nickname, :old_password)
  end
end

app/views/users/new.html.erb
<div class='form-page'>
    <div class='form-background'><div class='form-container'>
        <div class='main-label'>CREATE ACCOUNT</div>
        <%= form_with model: @user, url: users_path, method: :post do | form | %>
            <div class='<% if @user.errors[:login].present? %>error<% end %>'>
                <%= form.label "Login" %>
                <%= form.text_field :login, placeholder: 'Enter login' %>
                <%= render 'shared/error', model: @user, parametr: :login %>
            </div>
            <div class='<% if @user.errors[:password].present? %>error<% end %>'>
                <%= form.label "Password" %>
                <%= form.password_field :password, placeholder: 'Enter password' %>
                <%= render 'shared/error', model: @user, parametr: :password %>
            </div>
            <div class='<% if @user.errors[:password_confirmation].present? %>error<% end %>'>
                <%= form.label "Confirm password" %>
                <%= form.password_field :password_confirmation, placeholder: 'Confirm password' %>
                <%= render 'shared/error', model: @user, parametr: :password_confirmation %>
            </div>
            <div>
                <%= form.label "Nickname" %>
                <%= form.text_field :nickname, placeholder: 'Enter nickname', value: current_player&.nickname %>
            </div>
            <div class='pare-container'>
                <%= form.submit 'CREATE ACCOUNT', class: 'play-button' %>
            </div>
        <% end %>
        <hr>
        <%= button_to new_sessions_path, method: :get, class: "selection-option" do %>Log in<% end %>
        <%= button_to new_room_path, method: :get, class: "selection-option" do %>Play without account<% end %>
    </div></div>
</div>

app/views/users/show.html.erb
<%= @user.inspect %>

<div class='avatar'>
    <%= image_tag @user.avatar.url %>
</div>

<% if @user == current_user %>
    <%# поля для редактирования %>
<% end %>

<%# поля для изменения цветов %>
<%# показывать ли код комнаты по дефолту %>

<%# рейтинг? %>