config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get '/login', to: "home#login"

  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  # resources :guests, only: [:create, :destroy]

  resources :rooms, only: [:new, :create, :show]
  post '/rooms/join', to: 'rooms#join', as: 'rooms_join'
  delete '/rooms/:room_id/leave/:player_num', to: 'rooms#leave', as: 'rooms_leave'
  post '/rooms/:id/start', to: 'rooms#start', as: 'room_game_start'
  post '/rooms/:id/finish', to: 'rooms#finish', as: 'room_game_finish'
  patch '/rooms/:room_id/get_admin/:player_num', to: 'rooms#get_admin', as: 'room_get_admin'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_no_authenticate, only: [:login]

  def index
  end

  def login
    # @user = User.new
    # @guest = current_guest || Guest.new

    # @guests = Guest.all
  end
end

app/views/home/_info.html.erb
about creators

app/views/home/_shop.html.erb
<div class='form-background'><div class=''>
    shop
</div></div>

app/views/home/_user_window.html.erb
<div class='form-background'><div class=''>
    <% if user_signed_in? %>
        <%= link_to "Home", user_path(current_user), class: "selection-option" %>
        <%= button_to sessions_path, method: :delete, class: "selection-option" do %>Log out<% end %>
    <% else %>
        <%= button_to new_sessions_path, method: :get, class: "selection-option" do %>Log in<% end %>
        <%= button_to new_user_path, method: :get, class: "selection-option" do %>Create account<% end %>
    <% end %>
</div></div>

app/views/home/index.html.erb
<div class='center-container row'>
    <div class='center-container col'>
        <div class='center-container row'>
            <div>
                <%= image_tag 'logo' %>
                <%= link_to 'PLAY', new_room_path, class: 'play-button' %>
            </div>
            <div><%= render 'user_window' %></div>
        </div>
        <div><%= render 'info' %></div>
    </div>
    <div><%= render 'shop' %></div>
</div>