config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get '/login', to: "home#login"

  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  # resources :guests, only: [:create, :destroy]

  resources :rooms, only: [:new, :create, :show]
  post '/rooms/join', to: 'rooms#join', as: 'rooms_join'
  delete '/rooms/:room_id/leave/:player_num', to: 'rooms#leave', as: 'rooms_leave'
  post '/rooms/:id/start', to: 'rooms#start', as: 'room_game_start'
  post '/rooms/:id/finish', to: 'rooms#finish', as: 'room_game_finish'
  patch '/rooms/:room_id/get_admin/:player_num', to: 'rooms#get_admin', as: 'room_get_admin'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_players
  has_many :users, through: :room_players, source: :player, source_type: 'User'
  has_many :guests, through: :room_players, source: :player, source_type: 'Guest'

  before_validation :set_code_uppercase
  
  def initialize(attributes = {})
    super
    self.code = loop do
      random_code = SecureRandom.alphanumeric(4).upcase
      break random_code unless Room.exists?(code: random_code)
    end
  end

  private

  def set_code_uppercase
    self.code.upcase!
    self.code.gsub!(" ", "")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_player, only: [:new, :create, :join, :show]
  before_action :set_player_nickname, only: [:create, :join]
  before_action :is_player_in_room, only: [:show]
  before_action :set_code_uppercase, only: [:join]

  def new
    @room ||= Room.new
    @room_player = RoomPlayer.new(player: current_player, room: @room)
  end

  def create
    @room = Room.new
    @room.room_players.build(player: @player, is_admin: true)
    @room_player = @room.room_players.where(player: @player)
    @player.leave_room

    if @room.save
      redirect_to @room 
    else
      flash[:warning] = "Something get wrong. Try again"
      render :new
    end
  end

  def show
    @room ||= Room.find(params[:id])
    @room_players = @room.room_players
    @settings ||= {}
  end

  def join
    @room ||= Room.find_by(code: params.dig(:room_player, :code))
    @room_player = RoomPlayer.new(player: @player, room: @room)
    @player.leave_room
    if (@room)
      if (@room.game_start? && @player.room_player.room != @room)
        @room.errors.add(:code, "leads to the room that has already started the game") 
        render :new, status: :unprocessable_entity
      else 
        if (@room.room_players.create(player: @player))
          redirect_to @room  
        else 
          flash[:warning] = "Something get wrong. Try again"
          render :new, status: :unprocessable_entity
        end
      end
    else
      @room ||= Room.new
      @room.errors.add(:code, "doesn't exist")
      render :new, status: :unprocessable_entity
    end
  end

  def leave
    room = Room.find(params[:room_id])
    player = room.room_players.find_by(player_num: params[:player_num])
    if player
      player.destroy
      render json: { message: 'Player removed from room' }, status: :ok
    else
      render json: { error: 'Player not found' }, status: :not_found
    end    
  end

  def get_admin
    room = Room.find(params[:room_id])
    player = room.room_players.find_by(player_num: params[:player_num])
    if player && player.update({ :is_admin => true })
      render json: { message: 'Player got admin access' }, status: :ok
    else
      render json: { error: 'Player not found' }, status: :not_found
    end   
  end

  def start
    room = Room.find(params[:id])
    if room.update({ :game_start => true })
      render json: { message: 'Game in room #{params[:id]} started' }, status: :ok      
    else 
      render json: { error: 'Room not found' }, status: :not_found
    end
  end

  def finish
    room = Room.find(params[:id])
    if room.update({ :game_start => false })
      render json: { message: 'Game in room #{params[:id]} finished' }, status: :ok      
    else 
      render json: { error: 'Room not found' }, status: :not_found
    end
  end

  private

  def set_player
    @player = current_player
    return if @player.present?

    @player = Guest.new params.dig(:room_player, :nickname)
    while(!@player.save) do
      @player.session_token = SecureRandom.hex(16)
    end
    sign_in_guest( @player )
  end

  def set_player_nickname
    return if params.dig(:room_player, :nickname).nil?
    return if @player.nickname == params.dig(:room_player, :nickname)
    
    args = {}
    args[:nickname] = params.dig(:room_player, :nickname)
    return if @player.update args

    flash[:warning] = "Something get wrong. Try again"
    render :new, status: :unprocessable_entity
  end

  def is_player_in_room
    return if @player.room_player&.room_id == params[:id].to_i
    redirect_to new_room_path
  end

  def set_code_uppercase
    params.dig(:room_player, :code).upcase!
    params.dig(:room_player, :code).gsub!(" ", "")
  end
end

app/views/rooms/_desk.html.erb
<div class='form-page <% if !@room.game_start? %>hidden<% end %>' id='play-desk-block'>
    <canvas id='play-desk'></canvas>
    <button type='button' id='uno-button' onclick='say_uno()'>UNO</button>
    

    <%= render 'score' %>
</div>

app/views/rooms/_game_settings.html.erb
<div class='settings-block hidden-block<% if !@player.room_player.is_admin? %> admin-hidden<% end %>'>
    <%= form_with id: 'settings-form' do | form | %>
        <% Rules.all.each do | rule | %>
            <%= render 'setting', form: form, rule: rule %>
        <% end %>
    <% end %>
</div>

app/views/rooms/_player.html.erb
<div class='player-info-border<% if player == @player.room_player %> youself<% end %>' data-player-num='<%= player.player_num %>'>
    <div class='player-info'>
        <div class='avatar'>
            <%= image_tag player.player.avatar.url %>
        </div>
        <div class='nickname'><%= truncate player.player.nickname, length: 16 %></div>
        <button class='little-button get-admin<% if !@player.room_player.is_admin? %> admin-hidden<% end %><% if player == @player.room_player %> hidden<% end %>' onclick='get_admin(<%= player.player_num %>)' ></button>
        <button class='little-button remove-from-room<% if !@player.room_player.is_admin? %> admin-hidden<% end %><% if player == @player.room_player %> hidden<% end %>' onclick='remove_player(<%= player.player_num %>)' ></button>
    </div>
</div>

app/views/rooms/_score.html.erb
<div class='hidden' id='score-block'>
    <div class='form-background'><div>
        <p><span>GAME OVER</span></p>
        <p class='ps'>Your score: <span id='score'>0</span></p>
        <hr>
        <p>Returning to the room...</p>
    </div></div>
</div>

app/views/rooms/_setting.html.erb
<div class='setting-block-background'><div class='setting-block'>
    <div class='block'>
        <%= image_tag 'icon', class: 'icon' %>
    </div>
    <div class='block title'><%= rule.title %></div>
    <div class='block'><%= rule.description %></div>
    <div class='block'>
        <% case rule.option %>
        <% when 'check_box' %>
            <label class='checkbox-box'>
                <%= form.check_box rule.id, value: true %>
                <span class="slider"></span>
            </label>
        <% end %>       
    </div>
</div></div>

app/views/rooms/_textures.html.erb
<div class='hidden' id='assets-cards'>
    <%= image_tag 'cards/0.svg', id: '0' %>
    <%= image_tag 'cards/1.svg', id: '1' %>
    <%= image_tag 'cards/2.svg', id: '2' %>
    <%= image_tag 'cards/3.svg', id: '3' %>
    <%= image_tag 'cards/4.svg', id: '4' %>
    <%= image_tag 'cards/5.svg', id: '5' %>
    <%= image_tag 'cards/6.svg', id: '6' %>
    <%= image_tag 'cards/7.svg', id: '7' %>
    <%= image_tag 'cards/8.svg', id: '8' %>
    <%= image_tag 'cards/9.svg', id: '9' %>
    <%= image_tag 'cards/direction.svg', id: 'direction' %>
    <%= image_tag 'cards/skip.svg', id: 'skip' %>
    <%= image_tag 'cards/+2.svg', id: '+2' %>
    
    <%= image_tag 'cards/+4.svg', id: '+4' %>
    <%= image_tag 'cards/color_change.svg', id: 'color_change' %>

    <%= image_tag 'cards/back.svg', id: 'back' %>
    <%= image_tag 'cards/empty.svg', id: 'empty' %>
</div>

app/views/rooms/new.html.erb
<div class='form-page'>
    <div class='form-background'><div class='form-container'>
        <div class='main-label'>JOIN ROOM</div>

        <%= form_with model: @room_player, url: rooms_join_path, method: :post, id: 'join-room-form', html: { style: params.dig(:room_player, :submit_type) == 'create' ? 'display: none;' : '' } do | form | %>
            <%= form.hidden_field :submit_type, value: 'join'%>
            <div>
                <%= form.label "Nickname" %>
                <%= form.text_field :nickname, placeholder: 'Enter nickname', value: @player&.nickname %>
            </div>
            <div class='<% if @room.errors[:code].present? %>error<% end %>'>
                <%= form.label "Room code" %>
                <div class='pare-container'>
                    <%= form.text_field :code, placeholder: 'Code', value: params.dig(:room_player, :code) %>
                    <%= form.submit 'PLAY', class: 'play-button' %>
                </div>
                <%= render 'shared/error', model: @room, parametr: :code %>
            </div>
            <button type='button' class='selection-option', id="create-room-button">CREATE NEW ROOM</button>
        <% end %>

        <%= form_with model: @room_player, url: rooms_path, method: :post, id: 'create-room-form', html: { style: params.dig(:room_player, :submit_type) == 'create' ? '' : 'display: none;' } do | form | %>
            <%= form.hidden_field :submit_type, value: 'create' %>
            <div>
                <%= form.label "Nickname"%>
                <%= form.text_field :nickname, placeholder: 'Enter nickname', value: @player&.nickname %>
            </div>
            <div>
                <div class='pare-container'>
                    <%= form.submit 'PLAY', class: 'play-button' %>
                </div>
            </div>
            <button type='button' class='selection-option', id="join-room-button">JOIN OTHER ROOM</button>
        <% end %>
        <hr>
        <% if user_signed_in? %>
            <%= button_to sessions_path, method: :delete, class: "selection-option" do %>Log out<% end %>
        <% else %>
            <%= button_to new_sessions_path, method: :get, class: "selection-option" do %>Log in<% end %>
            <%= button_to new_user_path, method: :get, class: "selection-option" do %>Create account<% end %>
        <% end %>
    </div></div>
</div>

<%= javascript_include_tag "new_room_form", 'data-turbo-track': 'reload' %>

app/views/rooms/show.html.erb
<div class='form-page <% if @room.game_start? %>hidden<% end %>' id='room-form'
data-room-id='<%= @room.id %>' data-user-name='<%= @player.nickname %>' data-user-num='<%= @player.room_player.player_num %>' data-avatar='<%= @player.avatar.url %>'
<%= 'data-admin' if @player.room_player.is_admin %>/>
    <div class='form-background'><div class='room-container'>
        <div id='players'>
            <% @room_players.each do | player | %><%= render 'player', player: player %><% end %>
        </div>
        <button id='hidden-button' onclick='showBlock()'>Show game settings</button>
        <div>
            <div class='room-info'>
                <div id='code' data-link='<%= 'link' %>'><div class='back'><%= @room.code %></div></div>  
                <button class='setting-button-block' onclick='codeHideOrShow()'>
                    <div class='setting-button' id='hide-code'></div>
                    <div class='setting-button hidden' id='show-code'></div>
                    <p class='hide'>Hide room code</p>
                    <p class='show hidden'>Show room code</p>
                </button>
                <button class='setting-button-block' onclick='copyCode()'>
                    <div class='setting-button' id='copy-code'></div>
                    <p>Copy room code</p>
                </button>
                <button class='setting-button-block' onclick='copyLink()'>
                    <div class='setting-button' id='copy-link'></div>
                    <p>Copy link to room</p>
                </button>
            </div>
            <%= javascript_include_tag "copy_text", 'data-turbo-track': 'reload' %>
            <%= javascript_include_tag "hide_or_show_code", 'data-turbo-track': 'reload' %>
            
            <%= render 'game_settings' %>
            <div class='room-info'>
                <%= button_to new_room_path, method: :get, class: 'dangerous-button' do %>
                    LEAVE ROOM
                <% end %>
                <button id='start-game' class='play-button<% if !@player.room_player.is_admin? %> admin-hidden<% end %>'>START</button>
            </div>
        </div>
    </div></div><%= javascript_include_tag "transition_blocks", 'data-turbo-track': 'reload' %>
</div>

<%= render 'desk' %>
<%= render 'textures' %>

<script src="https://cdn.socket.io/4.0.0/socket.io.min.js"></script>
<%= javascript_include_tag "UI", 'data-turbo-track': 'reload' %>
<%= javascript_include_tag "game_draw", 'data-turbo-track': 'reload' %>
<%= javascript_include_tag "room_socket", 'data-turbo-track': 'reload' %>
<%= javascript_include_tag "play_socket", 'data-turbo-track': 'reload' %>
<%= javascript_include_tag "player_socket", 'data-turbo-track': 'reload' %>